robot_driver_node:
  ros__parameters:
    sdk_dir: /opt/genisom_l1_sdk
    sdk_module_name: mc_sdk_zsl_1w_py
    dog_ip: 192.168.234.1
    local_ip: 192.168.234.234
    local_port: 43988
    control_frequency: 10.0
    watchdog_timeout: 1.0
    max_linear_vel: 0.4
    max_angular_vel: 0.6
    poll_rate: 1.0